### ISSUE TITLE
Refactor VQE minimizer

### ISSUE THREAD

**Issue by scarrazza** [Quantum-TII/qibo#171]
In #139 we observe that the VQE.minimize is not used, in principle because the loss function cannot be disentangled from the VQE structure. We should refactor the VQE and try to modularize the code in such way that:
- the VQE accepts custom loss functions
- separate the ansatz from the VQE class
- the minimizer object can be used in other contexts, outside the VQE.

**Comment by stavros11** [comment]
Indeed this have been partially addressed when we created the `optimizers.py`. 

However, the idea behind this was that at some point we may want to move some of the algorithms used in the tutorial examples to actual Qibo models. I am not sure when we are planning to do that and whether our current VQE scheme is good for this or it requires further changes. We could probably close this issue in the sense that there is not much to do about it at the moment, but keep in mind that some further refactoring may be required if we decide to add new variational models.

**Comment by scarrazza** [comment]
Exactly, lets do that.
