### ISSUE TITLE
Invert/reverse circuits

### ISSUE THREAD

**Issue by igres26** [Quantum-TII/qibo#237]
As discussed, a useful tool to implement in Qibo would be an easy way to invert, or reverse existing circuits.

In several occasions quantum circuits require the inverse of a particular part of the circuit in order to complete the algorithm. This is true, for example, for Shor's algorithm as well as most Grover based algorithms including Amplitude Estimation.

A quick way of getting a circuit you have already created and get its inverse would help circuit design. This would require applying the dagger of all gates of the initial circuit in reverse order.

**Comment by scarrazza** [comment]
Thanks for reporting this. So you would like a method which reverses the current circuit or returns a new circuit?

**Comment by igres26** [comment]
Maybe it is better to return a new circuit, as this is normally used to add it into the main circuit.

**Comment by stavros11** [comment]
I started looking at this yesterday, I agree that returning a new circuit is convenient as one can create the total circuit by adding the original + any other gates + inverse.
Implementation of this should be easy, I just think we need to add a `dagger` method to all gates. I will try to propose something for this later today.
