### ISSUE TITLE
Check openqasm is cross platform

### ISSUE THREAD

**Issue by scarrazza** [Quantum-TII/qibo#244]
Following our discussion, we should try to check that the qasm generated by Qibo is compatible with other providers.
I believe would be great to have tests for the conversion between frameworks.

**Comment by scarrazza** [comment]
@stavros11 I have performed some tests and indeed the qasm generated from Qibo seems fully compatible with Qiskit. I have tested the qasm implementation in Cirq, however it does not support all gates, see table [here](https://github.com/quantumlib/Cirq/issues/1548#issuecomment-485039043).

If you agree, I will include minimal tests for Cirq and more extensive tests using Qiskit (creating an extra tests dependency).

**Comment by stavros11** [comment]
> If you agree, I will include minimal tests for Cirq and more extensive tests using Qiskit (creating an extra tests dependency).

Thanks for checking this, it would be good to have some tests. Looking at Cirq's table, I should also note that we also do not support all the Qasm gates. For example all commands denoted as NOT supported by Cirq (gate, opaque, reset, if and barrier) are also not supported from Qibo. Let me know if you believe that it would be useful to add support for some of these operations.
