### ISSUE TITLE
Collapse state during measurements

### ISSUE THREAD

**Issue by stavros11** [Quantum-TII/qibo#258]
Currently the measurement gate works by sampling the state vector and returning the sampled bit strings, however it does not have any effect on the state vector. This means that the final state of a circuit that contains measurements (which can be accessed as `circuit.final_state` after execution) is the same with the final state that we would get if the circuit contained no measurements. 

The state collapse is not done for two reasons:
1. It is not uniquely defined if `nshots > 1`. We would need to collapse to `nshots` different states and this would be memory inefficient. 
2. Not collapsing the state allows re-sampling it in case more measurement shots are needed.

On the other hand collapsing the state when `nshots = 1` is useful for some applications. I have an implementation of the collapse mechanism based on Tensorflow primitives that I will probably extend to custom operators for efficiency. The main question is what would be a good interface for this. I can think of the following possibilities:

* Add a new `gates.Collapse(*q, result)` gate that collapses qubits `*q` to the given `result` bit-string. This could be added in any place in the circuit as any other gates, but not after measurements on `*q` because currently we do not allow gates on measured qubits (after the measurement). This would be a bit counter-intuitive, given that the collapse typically happens after measurement, but it could still be a useful interface due to its flexibility.
* Integrate the collapse mechanism in the existing measurement gate `gates.M`, for example via a flag: `gates.M(*q, collapse=True)`. The collapse would only be possible when `nshots = 1` and would collapse the state to the measured result (which is selected probabilistically). This is less flexible than the previous interface which allowed the user to select the bit string to collapse to.

The second approach is also slightly more complicated in terms of implementation, because currently when `gates.M` is called on a state vector it returns a measurement object (and not a new state vector). All other gates return a state. If we do the collapse we would need to modify `gates.M` so that it returns the collapsed state and access the actual measurement result in a different way.

I am open to any other suggestions regarding an interface of this that you think it would be useful for applications.

**Comment by scarrazza** [comment]
Thanks for summarizing the case in study and proposing the interfaces. 

The first point sounds reasonable, in particular we could even consider the Collapse gate as a special measurement gate with `nshots=1` and specific bit-string result. Now, thinking about priority, if the problems we are planning solve matches the requirements of point 1 then we should go for it.
