### ISSUE TITLE
Wrong defined cost function in autoencoder tutorial

### ISSUE THREAD

**Issue by bpcarlos** [Quantum-TII/qibo#263]
I am now reproducing the results of the autoencoder tutorial, and I saw that someone changed the cost function, that is, the "encoder hamiltonian". The code looks better now, but the cost function has to be wrong defined. Why? Because it cannot go below 0 and it does. What we have now:

`encoder = 0.5 * (compress + 2*hamiltonians.Z(nqubits))`

What we had:

```
def encoder_hamiltonian(nqubits, ncompress):
        encoder = Hamiltonian(nqubits)
        encoder.hamiltonian = 0
        eye = matrices.I
        sz = matrices.Z
        for i in range(ncompress):
            h = 1
            for j in range(nqubits):
                if i == j:
                    h = np.kron(sz, h)
                else:
                    h = np.kron(eye, h)
            encoder.hamiltonian -= h
        
        h = 1
        for i in range(nqubits):
            h = np.kron(eye, h)        
        encoder.hamiltonian += ncompress*h
        encoder.hamiltonian /= 2
        return encoder
```

I believe the problem is that hamiltonians.Z(nqubits) has to be something like hamiltonians.Z(compress), and then some tensor product between that and identities to have the same dimension as identity(nqubits)*compress (?)

Note: in the definitions of hamiltonians.Y(nqubits) and hamiltonians.Z(nqubits) there is a typo where it says pauli-X in the description.

**Comment by stavros11** [comment]
Thanks for finding this. I must have changed that during some of the updates / attempts to simplify the tutorials as we were implementing new features in Qibo, but indeed the `0.5 * (compress + 2*hamiltonians.Z(nqubits))` does not agree with the one created by the function you write.

> I believe the problem is that hamiltonians.Z(nqubits) has to be something like hamiltonians.Z(compress), and then some tensor product between that and identities to have the same dimension as identity(nqubits)*compress (?)

Yes, the simplest way I could find to reproduce the correct Hamiltonian using Qibo's `hamiltonians.Z` follows this approach and is the following:
```Python
def encoder_hamiltonian_simple(nqubits, ncompress):
    m0 = hamiltonians.Z(ncompress, numpy=True).matrix
    m1 = np.eye(2 ** (nqubits - ncompress), dtype=m0.dtype)
    ham = hamiltonians.Hamiltonian(nqubits, np.kron(m1, m0))
    return 0.5 * (ham + ncompress)
```
The matrices generated by this agree with your function for various values of `nqubits` and `ncompress` if nqubits > ncompress (this is the only case, right?).

> Note: in the definitions of hamiltonians.Y(nqubits) and hamiltonians.Z(nqubits) there is a typo where it says pauli-X in the description.

Yes, thanks for spotting this. We should probably fix these two issues with a PR.

**Comment by bpcarlos** [comment]
Yes, that should be fine. Do you open the PR? I will open a PR soon with the new tutorial I am preparing, so would be great if we update to the new version asap. Thanks.

**Comment by stavros11** [comment]
> Yes, that should be fine. Do you open the PR? I will open a PR soon with the new tutorial I am preparing, so would be great if we update to the new version asap. Thanks.

I can open a PR for these two fixes but it should be reviewed before merging. If you are planning to open one anyway you can fix the Hamiltonian of the existing example there directly so that you have it fixed on the same branch. Don't worry about the docs, I can push the fix for this. Let me know whatever you prefer.

**Comment by bpcarlos** [comment]
OK, I will fix the cost function on the autoencoder example, no problem.

**Comment by bpcarlos** [comment]
@stavros11 I just found that the actual definition is not correct either. Imagine compress=2, then m0 is creating the operator Z_1 Z_2, right? What we actually need is the operator (Z_1 I + I Z_2 ) / 2 . I believe this in the first version was correct. Could you please confirm that? In that case, we should change the cost function in both the autoencoder and the EF-QAE tutorials.
