### ISSUE TITLE
Add Python 3.9 support

### ISSUE THREAD

**Issue by igres26** [Quantum-TII/qibo#302]
Are we supporting Python 3.9? I have been told that some errors popped up when trying to install Qibo through pip in Python 3.9.

Are we supporting it and this is an error, or is it not yet implemented?

The errors were:

```
ERROR: Could not find a version that satisfies the requirement qibo (from versions: none)
ERROR: No matching distribution found for qibo
```

**Comment by stavros11** [comment]
@scarrazza, this is the error I got on dom when I tried installing using the wheels. I think this should be easy to support if we just create a wheel for Python 3.9 which we don't have right now. The code should work as it is, in fact I think that already installing from source (clone the repository and do `python setup.py install && python setup.py build`) is possible with Python 3.9.

**Comment by scarrazza** [comment]
Yes, that's normal, because tf doesn't provide python 3.9 pip packages, but qibo is able to work on python3.9, if you compile tf from source with python3.9.

**Comment by scarrazza** [comment]
Related https://github.com/tensorflow/tensorflow/issues/44485
