### ISSUE TITLE
Controlled by gates with density matrices

### ISSUE THREAD

**Issue by stavros11** [Quantum-TII/qibo#342]
**Describe the bug**
Controlled gates that are created using the `controlled_by` method do not work with density matrices of 5 or more qubits if the `defaulteinsum` or `matmuleinsum` Tensorflow backends are used.

**To Reproduce**
```Python
import qibo
from qibo import gates, models
qibo.set_backend("defaulteinsum")

c = models.Circuit(5, density_matrix=True)
c.add(gates.H(1).controlled_by(0))
result = c()
```
leads to the following Tensorflow error:

```tensorflow.python.framework.errors_impl.UnimplementedError: Unhandled input dimensions 10 [Op:StridedSlice] name: strided_slice/```

The issue appears only for 5 or more qubits and only with the native tensorflow backends only. The numpy backends and the custom backend work without problem.

**Comment by scarrazza** [comment]
@stavros11 thanks for reporting this. Do you think is something we can fix or tf related? If is the latter, we can probably proceed with the release, otherwise we fix.
