### ISSUE TITLE
Improvements on drawing circuits.

### ISSUE THREAD

**Issue by igres26** [Quantum-TII/qibo#353]
Following some discussions with @joseignaciolatorre I would like to make some proposals on changes do the `.draw()` feature for ease of reading.

The `line_wrap` flag should be initialized at some value instead of being set to unlimited by default. We should decide a sensible value in order to not affect small and simple circuits, but at the same time if a large circuit needs to be drawn, have it split into chunks so that it can be properly interpreted.

Additionally, when splitting the circuits into different lines, it would be very useful to have the qubit labels repeated also on each new line in order to easily follow gates acting on a qubit on the following lines as well. The same argument can be made for having labels on the right side of the circuit as well.

If it does not crowd the screen too much, having extra qubit labels helps a lot when analyzing large circuits.

**Comment by scarrazza** [comment]
@igres26 thanks for the suggestion. Any guess for the line wrap default value or algorithm?

**Comment by igres26** [comment]
An algorithm might be best, but things depend too much on the display where the circuit is drawn. I think something around 70 (between 50 and 100) might be a good starting point.
