### ISSUE TITLE
Result from optimizers

### ISSUE THREAD

**Issue by lorenzoconfalonieri** [Quantum-TII/qibo#357]
Hi!
I was working with optimizers implemented in Qibo and I think it would be better if the optimizers returns more than only the value of the function and optimal parameters for example why the minimisation process has stoped, number of function evaluation etc...
Methods like "Powell" have also the possibility in SciPy to set bounds (not in dictionary "options") but this is not possible in Qibo.

Let me know what do you think about it. Thank you all!

**Comment by scarrazza** [comment]
@lorenzoconfalonieri thanks for reporting this, could you please have a look at this PR https://github.com/Quantum-TII/qibo/pull/358 and let me know if is sufficient?

**Comment by lorenzoconfalonieri** [comment]
I think it's perfect, thank you!
