### ISSUE TITLE
qibo.models could accept vectors as circuit parameters?

### ISSUE THREAD

**Issue by bpcarlos** [Quantum-TII/qibo#369]
I propose a simplification for the user and visual enhancement for qibo.models

**Is your feature request related to a problem? Please describe.**
Imagine we would like to compute expectation values for the following circuit 

```
def simple_circuit(parameter):
   circuit = models.Circuit(2)
   circuit.add(gates.RY(0, parameter))
   circuit.add(gates.RY(1, parameter))
   circuit.add(gates.CZ(0, 1))
   return circuit
```

We would like, however, to compute the expectation value of some _Hamiltonian_ for different input parameters. I believe, right now we should implement a _for loop_ for each of the parameters we are considering, something similar to this

```
expectation_values = []
params = [0,np.pi/2, np.pi/3, np.pi/4....]
for i in range(len(params)):
     expectation_values.append(Hamiltonian.expectation(simple_circuit(params[i]).execute()).numpy().real)
```

**Describe the solution you'd like**
I believe it would be more elegant if qibo.models accepts vectors as parameters, similar to other software for classical machine learning, e.g. Keras. A possible way to visualize it could be

```
params = [np.pi, np.pi/2, np.pi/3, np.pi/4....]
expectation_values = Hamiltonian.expectation(simple_circuit(params).execute()).numpy().real
```

where _expectation_values_ is now a vector of length _len(params)_ that contains the expectation values for the different input parameters.

**Comment by stavros11** [comment]
I think the first part of what is described is already implemented with `parallel.parallel_parametrized_execution`. You can execute a circuit for different values of the parameters in parallel as follows:

```Python
import numpy as np
from qibo import models, gates, parallel

# Define circuit using some initial parameter values
circuit = models.Circuit(2)
circuit.add(gates.RY(0, theta=0.0))
circuit.add(gates.RY(1, theta=0.0))
circuit.add(gates.CZ(0, 1))

# Create a list with the different parameter values you want to execute
params = np.array([0.0, 1/2, 1/3, 1/4]) * np.pi
params = list(np.reshape(np.repeat(params, 2, axis=0), (len(params), 2)))
# np.repeat is used here to create the following list:
# [[0, 0], [pi/2, pi/2], [pi/3, pi/3], ...]
# so that the same parameter value is used in both rotations as in your example

# execute in parallel
result = parallel.parallel_parametrized_execution(circuit, params)
```
Here `result` will be a list of four state objects which are the result of execution for each value of the parameters.

What is not possible right now is to get the expectation value in a "vectorized" way. If you use the above approach for your example you would still have to do a loop for the expectation value:
```Python
expectation_values = [Hamiltonian.expecation(r) for r in result]
```

Given that expectation values are somewhat important for optimization problems, it may be worth considering parallelizing this calculation.
