### ISSUE TITLE
Set device fails when used after set backend

### ISSUE THREAD

**Issue by stavros11** [Quantum-TII/qibo#374]
**Describe the bug**
`qibo.set_device()` does not have the expected behavior when used in the same script with `qibo.set_backend()`.

**To Reproduce**
```Python
import qibo
qibo.set_backend("custom")
qibo.set_device("/CPU:0")
print(qibo.get_device())
```
will print `"/GPU:0"` if executed in a machine with GPU enabled, as if the `qibo.set_device` instruction is ignored. If `set_backend` is not used then `set_device` works as intended.

**Comment by scarrazza** [comment]
I can reproduce this issue, and this sounds like the `_CONSTRUCTED_BACKENDS` and `K` are not in sync.

**Comment by scarrazza** [comment]
A simpler approach could be this: https://docs.python.org/3/faq/programming.html#id11

But probably will break many things, including user custom code.

**Comment by scarrazza** [comment]
Here some short version of the "singleton" approach we discussed today:

We place the following code in the `__init__.py` where `my_backend_object` is one of our backend inherited classes (e.g. `TensorflowBackend`):
```python
class backend:
    my_backend_object = 0
    _instance = None

    def __new__(cls, *args, **kwargs):
        if cls._instance is None:
            cls._instance = super(backend, cls).__new__(
                cls, *args, **kwargs)
        return cls._instance

    def __repr__(self):
        return repr(self.my_backend_object)


K = backend()
```
Then we can import K as usual and get the right object.
@stavros11 what do you think?

**Comment by stavros11** [comment]
Thanks for the details on this. I actually just pushed an update in #370 which I think is very close to this idea, excluding the `__new__` method which I think can be easily added. Please have a look and if you agree I can continue with this approach.
