### ISSUE TITLE
Optimizers documentation

### ISSUE THREAD

**Issue by DiegoGM91** [Quantum-TII/qibo#381]
There is a section in the documentation that I think that might lead to a confusion (as it happened to me). In particular, from [components/optimizers](https://qibo.readthedocs.io/en/stable/qibo.html#qibo.optimizers.cma), one could think that to access the options of the `cma` optimizer it suffices to type 
```python
from qibo.optimizers import cma
cma.CMAOptions()
```
which is not the case. Maybe the code to access the options,
```python
import cma
cma.CMAOptions()
```
could be stated more explicitly so as to avoid misunderstandings.

Also (although I found it clear enough) perhaps a sentence specifying that the user is not supposed to use the `qibo.optimizers.cma`, `qibo.optimizers.newtonian` and `qibo.optimizers.sgd` directly is worth including.

**Comment by scarrazza** [comment]
Thanks for spotting this issue. I think we can consider renaming the cma function to something different from the package name, e.g. `cmaes`.
