### ISSUE TITLE
set_parameters returns prints

### ISSUE THREAD

**Issue by bpcarlos** [Quantum-TII/qibo#386]
**Describe the bug**
I believe this is a bug of the new Qibo version. When you use the `circuit.set_parameters(params)` you receive as well some prints, so if you use it inside a loop you are basically receiving prints from circuit.set_parameters constantly.

`<qibo.backends.numpy.NumpyDefaultEinsumBackend object at 0x7f5042d8d240>`

**Comment by scarrazza** [comment]
Do you have a minimal example to reproduce this issue?

**Comment by stavros11** [comment]
There are several leftover prints in the `RZ` gate [here](https://github.com/Quantum-TII/qibo/blob/db9b79454d1bc7d0f716fa3f536e0e354386d86a/src/qibo/core/gates.py#L330), so I suspect this is the issue.

By the way, it would be a good idea if we could check that unwanted messages are not printed during testing. This way we could avoid such problems in the future.

**Comment by bpcarlos** [comment]
Yes, here it is:

```
def rotate(theta, x, layers=8, nqubits=1):
    new_theta = []
    index = 0
    for l in range(layers):
        for q in range(nqubits):
           new_theta.append(theta[index]*x + theta[index+1])
           index += 2
        for q in range(nqubits):
           new_theta.append(theta[index]*x + theta[index+1])
           index += 2
    return new_theta

circuit = models.Circuit(1)
for l in range(8):
    for q in range(1):
        circuit.add(gates.RY(q, theta=0))
    for q in range(nqubits):
        circuit.add(gates.RZ(q, theta=0))    
for i in range(200):
    newparams = rotate(params, 2)
    circuit.set_parameters(newparams)
```

I believe this should reproduce the error
