### ISSUE TITLE
linear.py cannot plot out other degenerations of the ground state

### ISSUE THREAD

**Issue by Haowen-Zou** [Quantum-TII/qibo#405]
I tried setting the h1(final Hamiltonian) as H = - \sum _{i＜j}  \\{ Z_i Z_j} , in this case, the ground state should have two degenerations(all ↑ state or all ↓ state). While linear.py only plots one situation. How do I apply check_degenerate in this case? Thank you.

**Comment by stavros11** [comment]
Thank you for looking into our examples. 

I think it depends on what exactly you would like to plot. Using the `h1.eigenvalues()` and `h1.eigenvectors()` methods you get the whole spectrum of the Hamiltonian, so `h1.eigenvalues()[0]` will give you the ground state energy and `h1.eigenvalues()[1]` will give you the second eigenvalue which in case of degeneracy will be the same as the first. Similarly:
```Python
h1.eigenvectors()[:, 0]
```
will give you the first eigenvector (in this case the |00...0> state) and 
```Python
h1.eigenvectors()[:, 1]
```
the second eigenvector |111...1>. Ofcourse all superpositions a|00...0> + b|11...1> are ground states too, but scipy doesn't know that so it just returns separate eigenvectors with the same energy.

You can use the above to adjust the plots accordingly. For example you can calculate two seperate overlaps with |00...0> and |11...1> by modifying the code as follows:
```Python
eigenvecs = h1.eigenvectors()
target_state1 = eigenvecs[:, 0] # |00...0>
target_state2 = eigenvecs[:, 1] # |11...1>

energy = callbacks.Energy(h1)
overlap1 = callbacks.Overlap(target_state1)
overlap2 = callbacks.Overlap(target_state2)
evolution = models.AdiabaticEvolution(h0, h1, lambda t: t, dt=dt,
                                          solver=solver,
                                          callbacks=[energy, overlap1, overlap2])
final_psi = evolution(final_time=T)
```
and then plot both overlaps as seperate lines in the same plot as:
```Python
plt.subplot(122)
plt.plot(tt, overlap1[:], linewidth=2.0)
plt.plot(tt, overlap2[:], linewidth=2.0, linestyle="--")
plt.xlabel("$t$")
plt.ylabel("Overlap")
```
Keep in mind though that this may not be very useful as the adiabatic evolution searches for the ground state of `h1` which in the degenerate case can be any superposition, so I guess it is not necessary that these overlaps will go to 1 but the energy may still approach the correct value. I'm not very familiar with the theory behind adiabatic evolution to talk more about this from the physics perspective though.

**Comment by Haowen-Zou** [comment]
Thank you so much for your help and answer, I think now I'm able to plot the other degenerate state. And just to check(since I'm a beginner for Python),what does the meaning of nunmber in [] of h1.eigenvector()[:, 1]? What if I want to know the overlap of state,say,11100 when nqubits＝5 ? Are I able to use h1.eigenvetor()[] or other ways?
Thank you.

**Comment by stavros11** [comment]
> Thank you so much for your help and answer, I think now I'm able to plot the other degenerate state. And just to check(since I'm a beginner for Python),what does the meaning of number in [] of h1.eigenvector()[:, 1]? 

`[]` is how you access the elements of a numpy array and other data structures (such as lists or tuples) in Python. See [indexing](https://numpy.org/doc/stable/reference/arrays.indexing.html) in the numpy documentation for more details. The `[:, 1]` used here returns the whole second column of an array with two dimensions (matrix). 

> What if I want to know the overlap of state,say,11100 when nqubits＝5 ? Are I able to use h1.eigenvetor()[] or other ways?

No, `h.eigenvectors()` returns the eigenvectors of the Hamiltonian `h` using the [`np.linalg.eigvalsh`](https://numpy.org/doc/stable/reference/generated/numpy.linalg.eigvalsh.html) (or the equivalent Tensorflow operation) and is not related to any overlap. If you want to calculate overlaps with other states you have to define them manually as arrays in the computational basis.

**Comment by Haowen-Zou** [comment]
> If you want to calculate overlaps with other states you have to define them manually as arrays in the computational basis.

Thank you for your help. But I'm still a little confused about how to define a state that I want, can you show me a simple example please?

**Comment by stavros11** [comment]
> Thank you for your help. But I'm still a little confused about how to define a state that I want, can you show me a simple example please?

You can define any state by writing the corresponding vector in the computational basis as an array. For example for 3 qubits the state vector should have 2^3=8 components so the |000> state would be:
```Python
state = np.array([1, 0, 0, 0, 0, 0, 0], dtype=np.complex128)
```
the (|000> + |111>) / sqrt(2) state would be:
```Python
state = np.array([1, 0, 0, 0, 0, 0, 1], dtype=np.complex128) / np.sqrt(2)
```
etc.. 

You can use any other way provided by numpy to define these arrays so that you don't have to write all elements explicitly. For example:
```Python
state = np.array([1, 0, 0, 0, 0, 0, 0], dtype=np.complex128)
```
is the same as
```Python
state = np.zeros(8, dtype=np.complex128)
state[0] = 1
```

**Comment by Haowen-Zou** [comment]
> If you have two state vectors `state1`, `state2` you can calculate the overlap |<state1 | state2>|^2 as:
> 
> ```Python
> 
> overlap = np.abs(np.dot(np.conj(state1), state2)) ** 2
> 
> ```
Thank you,I appreciate your time but sorry to trouble you again.Because when using the code you show me,I found out that I can't define the evolution, which lead the overlap outcome always equals to 1.
Can you show me how to define AdiabaticEvolution in this case please ?
Again,Thank you for your time.
